- name: Execute Production Contract Assertions
        run: bru run ping.bru --env Production --env-var system_token="${{ secrets.PROD_LIVE_BEARER_TOKEN }}" --env-var client_secret="${{ secrets.PROD_VAULT_PASSKEY }}"
